<?php

namespace App\Console\Commands;

use App\Brand;
use App\Category;
use App\SubCategory;
use Illuminate\Console\Command;

class FillBrands extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'fill:brands';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $brands = array(
            0 => array('name_en' => 'A. Favre & Fils', 'name_ar' => 'أ. فافر وفلس'),
            1 => array('name_en' => 'A. Lange & Söhne', 'name_ar' => 'أ. لانج وسون'),
            2 => array('name_en' => 'Aaron Lufkin Dennison', 'name_ar' => 'آرون لوفكين دينيسون'),
            3 => array('name_en' => 'Abraham-Louis Breguet', 'name_ar' => 'أبراهام لويس بريجيت'),
            4 => array('name_en' => 'ADINA Watches', 'name_ar' => 'ادينا'),
            5 => array('name_en' => 'Adrien Philippe', 'name_ar' => 'أدريان فيليب'),
            6 => array('name_en' => 'Alba', 'name_ar' => 'البا'),
            7 => array('name_en' => 'Alexander Shorokhoff', 'name_ar' => 'ألكسندر شوروخوف'),
            8 => array('name_en' => 'American Waltham Watch', 'name_ar' => 'الأمريكية والثام ووتش'),
            9 => array('name_en' => 'Andreas Strehler', 'name_ar' => 'أندرياس سترلر'),
            10 => array('name_en' => 'Anonimo', 'name_ar' => 'أنونيمو'),
            11 => array('name_en' => 'Ansonia Clock', 'name_ar' => 'ساعة أنسونيا'),
            12 => array('name_en' => 'Antoni Patek', 'name_ar' => 'أنتوني باتيك'),
            13 => array('name_en' => 'Apple Inc.', 'name_ar' => 'شركة أبل'),
            14 => array('name_en' => 'Aquastar', 'name_ar' => 'أكواستار'),
            15 => array('name_en' => 'Aragon', 'name_ar' => 'اراغون'),
            16 => array('name_en' => 'Armand Nicolet', 'name_ar' => 'أرماند نيكوليت'),
            17 => array('name_en' => 'Armani Exchange', 'name_ar' => 'أرماني للصرافة'),
            18 => array('name_en' => 'Armitron', 'name_ar' => 'أرميترون'),
            19 => array('name_en' => 'Ateliers deMonaco', 'name_ar' => 'أتيليرز ديموناكو'),
            20 => array('name_en' => 'Audemars Piguet', 'name_ar' => 'أودمارس بيجو'),
            21 => array('name_en' => 'Backes & Strauss', 'name_ar' => 'ظهورهم وشتراوس'),
            22 => array('name_en' => 'Ball Watch', 'name_ar' => 'مراقبة الكرة'),
            23 => array('name_en' => 'Baume et Mercier', 'name_ar' => 'باوم وآخرون مرسييه'),
            24 => array('name_en' => 'Bedat & Co', 'name_ar' => 'بيدات وشركاه'),
            25 => array('name_en' => 'Beijing Watch Factory', 'name_ar' => 'بكين مصنع ووتش'),
            26 => array('name_en' => 'Bell & Ross', 'name_ar' => 'بيل وروس'),
            27 => array('name_en' => 'Benetton Group', 'name_ar' => 'مجموعة بينيتون'),
            28 => array('name_en' => 'Benrus', 'name_ar' => 'بنروس'),
            29 => array('name_en' => 'Binda Group', 'name_ar' => 'مجموعة بيندا'),
            30 => array('name_en' => 'Blancpain', 'name_ar' => 'بلانكبين'),
            31 => array('name_en' => 'Blumarine', 'name_ar' => 'بلومارين'),
            32 => array('name_en' => 'Bovet Fleurier', 'name_ar' => 'بوفيه فلورييه'),
            33 => array('name_en' => 'Bozeman Watch', 'name_ar' => 'مراقبة بوزمان'),
            34 => array('name_en' => 'Breguet', 'name_ar' => 'بريجيت'),
            35 => array('name_en' => 'Breil', 'name_ar' => 'بريل'),
            36 => array('name_en' => 'Breitling', 'name_ar' => 'بريتلينغ'),
            37 => array('name_en' => 'Bremont Watch', 'name_ar' => 'بريمونت ووتش'),
            38 => array('name_en' => 'Buccellati', 'name_ar' => 'بوكسيلاتي'),
            39 => array('name_en' => 'Bulgari', 'name_ar' => 'بلغاري'),
            40 => array('name_en' => 'Bulova', 'name_ar' => 'بولوفا'),
            41 => array('name_en' => 'Burberry', 'name_ar' => 'بربري'),
            42 => array('name_en' => 'Carl F. Bucherer', 'name_ar' => 'كارل ف. بوشر'),
            43 => array('name_en' => 'Carlo Ferrara', 'name_ar' => 'كارلو فيرارا'),
            44 => array('name_en' => 'Cartier', 'name_ar' => 'كارتييه'),
            45 => array('name_en' => 'Casio', 'name_ar' => 'كاسيو'),
            46 => array('name_en' => 'Catorex', 'name_ar' => 'كاتوريكس'),
            47 => array('name_en' => 'Cecil Purnell', 'name_ar' => 'سيسيل بورنل'),
            48 => array('name_en' => 'Century Time Gems Ltd', 'name_ar' => 'قرن الوقت الأحجار الكريمة المحدودة'),
            49 => array('name_en' => 'Certina', 'name_ar' => 'سيرتينا'),
            50 => array('name_en' => 'Chanel', 'name_ar' => 'شانيل'),
            51 => array('name_en' => 'Charles Frodsham', 'name_ar' => 'تشارلز فرودشام'),
            52 => array('name_en' => 'Charriol', 'name_ar' => 'شاريول'),
            53 => array('name_en' => 'Chopard', 'name_ar' => 'شوبارد'),
            54 => array('name_en' => 'Christian Jacques', 'name_ar' => 'كريستيان جاك'),
            55 => array('name_en' => 'Christopher Ward', 'name_ar' => 'كريستوفر وارد'),
            56 => array('name_en' => 'Chronoswiss', 'name_ar' => 'كرونوسويس'),
            57 => array('name_en' => 'Chung nam group', 'name_ar' => 'تشونغ نام المجموعة'),
            58 => array('name_en' => 'Citizen Watch Co.', 'name_ar' => 'شركة مراقبة المواطن'),
            59 => array('name_en' => 'Ck Calvin Klein', 'name_ar' => 'كِك كالفن كلاين'),
            60 => array('name_en' => 'Concord', 'name_ar' => 'كونكورد'),
            61 => array('name_en' => 'Corum', 'name_ar' => 'كوروم'),
            62 => array('name_en' => 'Curtis Australia', 'name_ar' => 'كورتيس أستراليا'),
            63 => array('name_en' => 'Cyma Watches', 'name_ar' => 'ساعات سايما'),
            64 => array('name_en' => 'D. Dornblüth & Sohn', 'name_ar' => 'د. دورنبلوث وسون'),
            65 => array('name_en' => 'D1 Milano', 'name_ar' => 'دي ون ميلانو'),
            66 => array('name_en' => 'Dakota Watch', 'name_ar' => 'داكوتا ووتش'),
            67 => array('name_en' => 'Damasko', 'name_ar' => 'داماسكو'),
            68 => array('name_en' => 'Damiani', 'name_ar' => 'دامياني'),
            69 => array('name_en' => 'Dan Henry Watches', 'name_ar' => 'دان هنري ساعات'),
            70 => array('name_en' => 'Daniel Roth', 'name_ar' => 'دانيال روث'),
            71 => array('name_en' => 'Daniel Wellington', 'name_ar' => 'دانيال ويلينغتون'),
            72 => array('name_en' => 'David Ramsay', 'name_ar' => 'ديفيد رامزي'),
            73 => array('name_en' => 'Dior', 'name_ar' => 'ديور'),
            74 => array('name_en' => 'Doxa S.A.', 'name_ar' => 'دوكسا س. أ.'),
            75 => array('name_en' => 'Dreffa', 'name_ar' => 'دريفا'),
            76 => array('name_en' => 'Dubey Schaldenbrand', 'name_ar' => 'دوبي شالدنبراند'),
            77 => array('name_en' => 'Dueber-Hampden Watch', 'name_ar' => 'ساعة دوبير-هامبدن'),
            78 => array('name_en' => 'Ebel', 'name_ar' => 'ابل'),
            79 => array('name_en' => 'Eberhard & Co.', 'name_ar' => 'إبرهارد وشركاه'),
            80 => array('name_en' => 'Edouard Bovet', 'name_ar' => 'إدوارد بوفيه'),
            81 => array('name_en' => 'Edox', 'name_ar' => 'إدوك'),
            82 => array('name_en' => 'Edward John Dent', 'name_ar' => 'إدوارد جون دينت'),
            83 => array('name_en' => 'Elgin National Watch', 'name_ar' => 'إلجين ناشيونال ووتش'),
            84 => array('name_en' => 'Emporio Armani', 'name_ar' => 'إمبوريو أرماني'),
            85 => array('name_en' => 'Endura Watch Factory', 'name_ar' => 'مصنع إندورا للساعات'),
            86 => array('name_en' => 'EPOS', 'name_ar' => 'أي بوس'),
            87 => array('name_en' => 'Ernest Borel', 'name_ar' => 'إرنست بوريل'),
            88 => array('name_en' => 'ESPRIT', 'name_ar' => 'اسبري'),
            89 => array('name_en' => 'Eterna', 'name_ar' => 'أبدية'),
            90 => array('name_en' => 'F.P. Journe', 'name_ar' => 'ف. ب. جورني'),
            91 => array('name_en' => 'Fastrack', 'name_ar' => 'فاستراك'),
            92 => array('name_en' => 'Favre-Leuba', 'name_ar' => 'فافر- ليوبا'),
            93 => array('name_en' => 'Fendi', 'name_ar' => 'فيندي'),
            94 => array('name_en' => 'Festina', 'name_ar' => 'فيستينا'),
            95 => array('name_en' => 'Fila', 'name_ar' => 'فيلا'),
            96 => array('name_en' => 'Fitbit', 'name_ar' => 'فيتبيت'),
            97 => array('name_en' => 'Folli Follie', 'name_ar' => 'فولي فولي'),
            98 => array('name_en' => 'Fortis Uhren', 'name_ar' => 'فورتيس أوهرين'),
            99 => array('name_en' => 'Fossil, Inc.', 'name_ar' => 'شركة فوسيل'),
            100 => array('name_en' => 'Franck Muller', 'name_ar' => 'فرانك مولر'),
            101 => array('name_en' => 'Franck Muller', 'name_ar' => 'فرانك مولر'),
            102 => array('name_en' => 'Frédérique Constant', 'name_ar' => 'فريديريك كونستانت'),
            103 => array('name_en' => 'French Connection', 'name_ar' => 'اتصال الفرنسية'),
            104 => array('name_en' => 'Gallet & Co.', 'name_ar' => 'جاليت وشركاه'),
            105 => array('name_en' => 'Garmin', 'name_ar' => 'غارمين'),
            106 => array('name_en' => 'General Watch Co', 'name_ar' => 'شركة المراقبة العامة'),
            107 => array('name_en' => 'Georg Jensen', 'name_ar' => 'جورج جنسن'),
            108 => array('name_en' => 'George Daniels', 'name_ar' => 'جورج دانيلز'),
            109 => array('name_en' => 'George Graham', 'name_ar' => 'جورج غراهام'),
            110 => array('name_en' => 'Girard-Perregaux', 'name_ar' => 'جيرارد-بيريغو'),
            111 => array('name_en' => 'Glashütte Original', 'name_ar' => 'غلاشوت الأصلي'),
            112 => array('name_en' => 'Glycine Watch', 'name_ar' => 'مراقبة الجليسين'),
            113 => array('name_en' => 'Greubel Forsey', 'name_ar' => 'غريوبيل فورسي'),
            114 => array('name_en' => 'Grovana Watch', 'name_ar' => 'ساعة جروفانا'),
            115 => array('name_en' => 'Guess Watches Co.', 'name_ar' => 'تخمين الساعات شركة'),
            116 => array('name_en' => 'Gustav Bruemmer', 'name_ar' => 'غوستاف برومر'),
            117 => array('name_en' => 'Halda Watch', 'name_ar' => 'هالدا ووتش'),
            118 => array('name_en' => 'Hamilton Watch', 'name_ar' => 'هاميلتون ووتش'),
            119 => array('name_en' => 'Hangzhou Watch', 'name_ar' => 'هانغتشو ووتش'),
            120 => array('name_en' => 'Hanhart', 'name_ar' => 'هانهارت'),
            121 => array('name_en' => 'Hanowa', 'name_ar' => 'هاناوا'),
            122 => array('name_en' => 'Harry Winston', 'name_ar' => 'هاري وينستون'),
            123 => array('name_en' => 'Hawler', 'name_ar' => 'هالر'),
            124 => array('name_en' => 'Henry Pitkin', 'name_ar' => 'هنري بيتكين'),
            125 => array('name_en' => 'Hermès', 'name_ar' => 'هيرميس'),
            126 => array('name_en' => 'Hublot', 'name_ar' => 'هوبلوت'),
            127 => array('name_en' => 'Ikepod', 'name_ar' => 'إيكيبود'),
            128 => array('name_en' => 'Illinois Watch', 'name_ar' => 'إلينوي ووتش'),
            129 => array('name_en' => 'International Watch', 'name_ar' => 'المراقبة الدولية'),
            130 => array('name_en' => 'Invicta Watch Group', 'name_ar' => 'مجموعة إنفيكتا رايتس ووتش'),
            131 => array('name_en' => 'Jacob & Co', 'name_ar' => 'جاكوب وشركاه'),
            132 => array('name_en' => 'Jaeger-LeCoultre', 'name_ar' => 'جيجر- لوكولتر'),
            133 => array('name_en' => 'Jean Lassale', 'name_ar' => 'جان لاسالي'),
            134 => array('name_en' => 'Jean Perret', 'name_ar' => 'جان بيريه'),
            135 => array('name_en' => 'John Arnold', 'name_ar' => 'جون أرنولد'),
            136 => array('name_en' => 'John Harrison', 'name_ar' => 'جون هاريسون'),
            137 => array('name_en' => 'Jorg Gray', 'name_ar' => 'يورغ جراي'),
            138 => array('name_en' => 'Joseph Windmills', 'name_ar' => 'جوزيف طواحين الهواء'),
            139 => array('name_en' => 'Jowissa', 'name_ar' => 'جويسا'),
            140 => array('name_en' => 'Jules Jurgensen', 'name_ar' => 'جولز يورغنسن'),
            141 => array('name_en' => 'Junghans', 'name_ar' => 'يونغهانس'),
            142 => array('name_en' => 'Karsten Frässdorf', 'name_ar' => 'كارستن فنسدورف'),
            143 => array('name_en' => 'Kienzle', 'name_ar' => 'كينزل'),
            144 => array('name_en' => 'Laco Uhrenmanufaktur', 'name_ar' => 'لاكو أوهرنمانوفاكتور'),
            145 => array('name_en' => 'Lancashire Watch', 'name_ar' => 'لانكشاير ووتش'),
            146 => array('name_en' => 'Lang & Heyne', 'name_ar' => 'لانغ وهاين'),
            147 => array('name_en' => 'Leijona Watch', 'name_ar' => 'ليجونا ووتش'),
            148 => array('name_en' => 'Lemania', 'name_ar' => 'ليمانا'),
            149 => array('name_en' => 'Léon Gallet', 'name_ar' => 'ليون غاليت'),
            150 => array('name_en' => 'Lilienthal Berlin', 'name_ar' => 'ليلينتال برلين'),
            151 => array('name_en' => 'Linde Werdelin', 'name_ar' => 'ليندي فيرديلين'),
            152 => array('name_en' => 'Lip', 'name_ar' => 'الشفه'),
            153 => array('name_en' => 'Locman', 'name_ar' => 'لوكمان'),
            154 => array('name_en' => 'Longines', 'name_ar' => 'لونجين'),
            155 => array('name_en' => 'Louis Erard', 'name_ar' => 'لويس إيرارد'),
            156 => array('name_en' => 'Louis George', 'name_ar' => 'لويس جورج'),
            157 => array('name_en' => 'Louis Moinet', 'name_ar' => 'لويس موينيه'),
            158 => array('name_en' => 'Luch', 'name_ar' => 'لوش'),
            159 => array('name_en' => 'Luminox', 'name_ar' => 'لوميناكس'),
            160 => array('name_en' => 'Maitres du Temps', 'name_ar' => 'الماجستير من الزمن'),
            161 => array('name_en' => 'Manhattan Watch', 'name_ar' => 'مانهاتن ووتش'),
            162 => array('name_en' => 'Manistee Watch', 'name_ar' => 'مانيستي ووتش'),
            163 => array('name_en' => 'Manufacture royale', 'name_ar' => 'التصنيع الملكي'),
            164 => array('name_en' => 'Marc Ecko', 'name_ar' => 'مارك إيكو'),
            165 => array('name_en' => 'Mathey-Tissot', 'name_ar' => 'ماثي تيسو'),
            166 => array('name_en' => 'Maurice Lacroix', 'name_ar' => 'موريس لاكروا'),
            167 => array('name_en' => 'MeisterSinger', 'name_ar' => 'مايسترزينغر'),
            168 => array('name_en' => 'Melbourne Watch', 'name_ar' => 'ملبورن ووتش'),
            169 => array('name_en' => 'Mido', 'name_ar' => 'ميدو'),
            170 => array('name_en' => 'Molnija', 'name_ar' => 'مولنيجا'),
            171 => array('name_en' => 'Mondaine', 'name_ar' => 'الدنيويه'),
            172 => array('name_en' => 'Montblanc', 'name_ar' => 'مون بلان'),
            173 => array('name_en' => 'Montegrappa', 'name_ar' => 'مونتيغرابا'),
            174 => array('name_en' => 'Morellato Group', 'name_ar' => 'مجموعة موريلاتو'),
            175 => array('name_en' => 'Moritz Grossmann', 'name_ar' => 'موريتز غروسمان'),
            176 => array('name_en' => 'Moschino', 'name_ar' => 'موسكينو'),
            177 => array('name_en' => 'Mossimo', 'name_ar' => 'موسيمو'),
            178 => array('name_en' => 'Movado', 'name_ar' => 'موفادو'),
            179 => array('name_en' => 'Newgate Watches', 'name_ar' => 'الساعات نيوجيت'),
            180 => array('name_en' => 'Nike Inc.', 'name_ar' => 'شركة نايكي'),
            181 => array('name_en' => 'Nivada', 'name_ar' => 'نيفادا'),
            182 => array('name_en' => 'Nixon Watches', 'name_ar' => 'نيكسون ساعات'),
            183 => array('name_en' => 'Nomos Glashütte', 'name_ar' => 'نوموس غلاشوت'),
            184 => array('name_en' => 'Ollech & Wajs', 'name_ar' => 'أوليش وواج'),
            185 => array('name_en' => 'Omega SA', 'name_ar' => 'أوميغا SA'),
            186 => array('name_en' => 'Orfina', 'name_ar' => 'أورفينا'),
            187 => array('name_en' => 'Orient Watch Co., Ltd.', 'name_ar' => 'شركة أورينت ووتش المحدودة'),
            188 => array('name_en' => 'Oris', 'name_ar' => 'أوريس'),
            189 => array('name_en' => 'Parmigiani Fleurier', 'name_ar' => 'باريميجياني فلورييه'),
            190 => array('name_en' => 'Parnis Watches', 'name_ar' => 'ساعات بارنيس'),
            191 => array('name_en' => 'Patek Philippe & Co.', 'name_ar' => 'باتيك فيليب وشركاه'),
            192 => array('name_en' => 'Pequignet', 'name_ar' => 'بيكيغنيت'),
            193 => array('name_en' => 'Perrelet', 'name_ar' => 'بيريليت'),
            194 => array('name_en' => 'Peter Litherland', 'name_ar' => 'بيتر ليثيرلاند'),
            195 => array('name_en' => 'Petrodvorets', 'name_ar' => 'بترودفوريتس'),
            196 => array('name_en' => 'Philip Watch', 'name_ar' => 'فيليب ووتش'),
            197 => array('name_en' => 'Philip Zepter', 'name_ar' => 'فيليب زيبتر'),
            198 => array('name_en' => 'Pierre Jaquet-Droz', 'name_ar' => 'بيير جاكيه-دروز'),
            199 => array('name_en' => 'Pobeda', 'name_ar' => 'بوبيدا'),
            200 => array('name_en' => 'Police', 'name_ar' => 'الشرطه'),
            201 => array('name_en' => 'Poljot', 'name_ar' => 'بولجوت'),
            202 => array('name_en' => 'Prada', 'name_ar' => 'برادا'),
            203 => array('name_en' => 'Pulsar', 'name_ar' => 'بولسار'),
            204 => array('name_en' => 'Rado', 'name_ar' => 'رادو'),
            205 => array('name_en' => 'Raketa', 'name_ar' => 'راكيتا'),
            206 => array('name_en' => 'Raymond Weil', 'name_ar' => 'ريمون ويل'),
            207 => array('name_en' => 'Regina', 'name_ar' => 'ريجينا'),
            208 => array('name_en' => 'Reguladora', 'name_ar' => 'ريجولادورا'),
            209 => array('name_en' => 'Ressence', 'name_ar' => 'إعادة الانسة'),
            210 => array('name_en' => 'Revue Thommen', 'name_ar' => 'ريفو تومين'),
            211 => array('name_en' => 'Richard Mille', 'name_ar' => 'ريتشارد ميل'),
            212 => array('name_en' => 'Roamer', 'name_ar' => 'رومير'),
            213 => array('name_en' => 'Rodania', 'name_ar' => 'رودانيا'),
            214 => array('name_en' => 'Roger Dubuis', 'name_ar' => 'روجر دوبوا'),
            215 => array('name_en' => 'Roger W. Smith', 'name_ar' => 'روجر سميث'),
            216 => array('name_en' => 'Rolex', 'name_ar' => 'رولكس'),
            217 => array('name_en' => 'Romain Gauthier', 'name_ar' => 'رومان غوتييه'),
            218 => array('name_en' => 'Ronda AG', 'name_ar' => 'روندا أي جي'),
            219 => array('name_en' => 'ROSTAM', 'name_ar' => 'رستم'),
            220 => array('name_en' => 'Rotary Watches', 'name_ar' => 'ساعات الروتاري'),
            221 => array('name_en' => 'Sandoz watches', 'name_ar' => 'ساعات ساندوز'),
            222 => array('name_en' => 'Schwarz Etienne', 'name_ar' => 'شوارز إتيان'),
            223 => array('name_en' => 'Sea-Gull', 'name_ar' => 'سي-نورس'),
            224 => array('name_en' => 'Sector', 'name_ar' => 'القطاع'),
            225 => array('name_en' => 'Seiko', 'name_ar' => 'سايكو'),
            226 => array('name_en' => 'Seiko Epson', 'name_ar' => 'سيكو إبسون'),
            227 => array('name_en' => 'Seiko Instruments', 'name_ar' => 'سيكو الصكوك'),
            228 => array('name_en' => 'Seikosha', 'name_ar' => 'سيكوشا'),
            229 => array('name_en' => 'Sekonda', 'name_ar' => 'سيكوندا'),
            230 => array('name_en' => 'Seth Thomas', 'name_ar' => 'سيث توماس'),
            231 => array('name_en' => 'Shanghai Watch Co.', 'name_ar' => 'شنغهاي ووتش كو'),
            232 => array('name_en' => 'Shinola Detroit', 'name_ar' => 'شينولا ديترويت'),
            233 => array('name_en' => 'Sinn', 'name_ar' => 'الخطيئة'),
            234 => array('name_en' => 'Skagen Designs', 'name_ar' => 'سكاجن تصاميم'),
            235 => array('name_en' => 'Slava watches', 'name_ar' => 'ساعات سلافا'),
            236 => array('name_en' => 'Slow watch', 'name_ar' => 'ساعة بطيئة'),
            237 => array('name_en' => 'Solvil et Titus', 'name_ar' => 'سولابيل وتيتوس'),
            238 => array('name_en' => 'Star Watch Case', 'name_ar' => 'حالة مراقبة النجوم'),
            239 => array('name_en' => 'Stauer', 'name_ar' => 'ستاور'),
            240 => array('name_en' => 'Stepan Sarpaneva', 'name_ar' => 'ستيبان ساربانيفا'),
            241 => array('name_en' => 'Stührling', 'name_ar' => 'شتوهرلينغ'),
            242 => array('name_en' => 'Suunto', 'name_ar' => 'سونتو'),
            243 => array('name_en' => 'Swatch Group', 'name_ar' => 'مجموعة سواتش'),
            244 => array('name_en' => 'TAG Heuer', 'name_ar' => 'تاغ هوير'),
            245 => array('name_en' => 'Technos', 'name_ar' => 'تكنوس'),
            246 => array('name_en' => 'Thomas Earnshaw', 'name_ar' => 'توماس إيرنشو'),
            247 => array('name_en' => 'Thomas Tompion', 'name_ar' => 'توماس تومبيون'),
            248 => array('name_en' => 'Tianjin Sea-Gull', 'name_ar' => 'تيانجين بحر-نورس'),
            249 => array('name_en' => 'Tiffany & Co', 'name_ar' => 'تيفاني وشركاه'),
            250 => array('name_en' => 'Timex Group', 'name_ar' => 'مجموعة تايم إكس'),
            251 => array('name_en' => 'Tissot', 'name_ar' => 'تيسو'),
            252 => array('name_en' => 'Titan Industries', 'name_ar' => 'تيتان للصناعات'),
            253 => array('name_en' => 'Titoni', 'name_ar' => 'تيتوني'),
            254 => array('name_en' => 'Tommy Hilfiger', 'name_ar' => 'تومي هيلفيغر'),
            255 => array('name_en' => 'Tourneau', 'name_ar' => 'تورناو'),
            256 => array('name_en' => 'Tudor', 'name_ar' => 'تيودور'),
            257 => array('name_en' => 'Tutima', 'name_ar' => 'توتيما'),
            258 => array('name_en' => 'Ulysse Nardin', 'name_ar' => 'يوليس ناردين'),
            259 => array('name_en' => 'Universal Genève', 'name_ar' => 'جنيف العالمي'),
            260 => array('name_en' => 'Vacheron Constantin', 'name_ar' => 'فاشيرون كونستانتين'),
            261 => array('name_en' => 'Vacuum Chronometer Corporation', 'name_ar' => 'فراغ كرونومتر شركة'),
            262 => array('name_en' => 'Valjoux', 'name_ar' => 'فالجو'),
            263 => array('name_en' => 'Versus', 'name_ar' => 'مقابل'),
            264 => array('name_en' => 'Visconti', 'name_ar' => 'فيسكونتي'),
            265 => array('name_en' => 'Vostok watches', 'name_ar' => 'ساعات فوستوك'),
            266 => array('name_en' => 'Waltham International SA', 'name_ar' => 'والثام الدولية SA'),
            267 => array('name_en' => 'Waltham Watch', 'name_ar' => 'ساعة والثام'),
            268 => array('name_en' => 'Webb C. Ball', 'name_ar' => 'ويب C. الكرة'),
            269 => array('name_en' => 'Wenger', 'name_ar' => 'فينغر'),
            270 => array('name_en' => 'West End Watch Co', 'name_ar' => 'ويست إند ووتش كو'),
            271 => array('name_en' => 'Westclox', 'name_ar' => 'ويستكلوس'),
            272 => array('name_en' => 'WeWOOD', 'name_ar' => 'ووود'),
            273 => array('name_en' => 'Wittnauer', 'name_ar' => 'فيتناور'),
            274 => array('name_en' => 'Wyler', 'name_ar' => 'وايلر'),
            275 => array('name_en' => 'Xezo', 'name_ar' => 'زيزو'),
            276 => array('name_en' => 'Yema', 'name_ar' => 'يما'),
            277 => array('name_en' => 'Zenith', 'name_ar' => 'زينيث'),
            278 => array('name_en' => 'Zeno-Watch Basel', 'name_ar' => 'زينو-ووتش بازل'),
            279 => array('name_en' => 'Zodiac', 'name_ar' => 'زودياك'),
            280 => array('name_en' => 'Others', 'name_ar' => 'أخرى'),
        );
        $SubCategory = SubCategory::find(4);
        

            foreach ($brands as $brand){
                $SubCategory->brands()->attach($brand);
            }
        



        $this->info('|----------------------------------|');
        $this->info('| Seeding Electronics Done Successfully |');
        $this->info('|----------------------------------|');
    }
}
