<?php

namespace App\Console\Commands;

use App\Brand;
use App\Category;
use App\SubCategory;
use Illuminate\Console\Command;

class FillBrands extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'fill:brands';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $data = [
            ['name_en' => '3M', 'name_ar' => 'ثري ام'],
            ['name_en' => 'Acer', 'name_ar' => '‏  اسير'],
            ['name_en' => 'Aigo ', 'name_ar' => 'ايجو'],
            ['name_en' => 'Alba', 'name_ar' => 'البا'],
            ['name_en' => 'Alfa', 'name_ar' => 'الفا'],
            ['name_en' => 'Allied Telesis – NW, OEE', 'name_ar' => 'آليد تليسيس'],
            ['name_en' => 'Alpine – CA, CN', 'name_ar' => 'البين'],
            ['name_en' => 'Amazon', 'name_ar' => 'امازون'],
            ['name_en' => 'AMD', 'name_ar' => 'اي ام دي'],
            ['name_en' => 'Amkette', 'name_ar' => 'أمكيت'],
            ['name_en' => 'Amoi', 'name_ar' => 'اومي'],
            ['name_en' => 'Amstrad', 'name_ar' => 'امستراد'],
            ['name_en' => 'Analog Devices', 'name_ar' => 'انالوق ديفيفس'],
            ['name_en' => 'AOC (AOC International) ((TPV Technology Limited))', 'name_ar' => 'اوسي'],
            ['name_en' => 'Aopen', 'name_ar' => '‏  اوبن'],
            ['name_en' => 'Apple', 'name_ar' => 'ابل'],
            ['name_en' => 'Arçelik', 'name_ar' => 'أرتشيليك'],
            ['name_en' => 'Aselsan', 'name_ar' => 'اسيلسان'],
            ['name_en' => 'Asus', 'name_ar' => 'اسوس'],
            ['name_en' => 'Audiovox', 'name_ar' => 'أوديوفوكس'],
            ['name_en' => 'Avaya', 'name_ar' => 'افايا'],
            ['name_en' => 'Averatec', 'name_ar' => 'افراتيك'],
            ['name_en' => 'Avibras', 'name_ar' => 'أفبراس'],
            ['name_en' => 'BAE Systems', 'name_ar' => 'بي أيه أي سيستمز'],
            ['name_en' => 'Beetel', 'name_ar' => 'بيتل'],
            ['name_en' => 'Beko', 'name_ar' => 'بيكو'],
            ['name_en' => 'BenQ', 'name_ar' => '‏  بين كيو'],
            ['name_en' => 'Bharat Electronics', 'name_ar' => 'بارات اليكترونيكس'],
            ['name_en' => 'Binatone', 'name_ar' => 'بيناتون'],
            ['name_en' => 'BlackBerry Limited (as BlackBerry)', 'name_ar' => 'بلاك بيري لمتد'],
            ['name_en' => 'Blaupunkt', 'name_ar' => 'بلوبونكت'],
            ['name_en' => 'Bosch', 'name_ar' => 'بوش'],
            ['name_en' => 'Bose', 'name_ar' => 'بوز'],
            ['name_en' => 'Bose', 'name_ar' => 'بوز'],
            ['name_en' => 'BPL', 'name_ar' => 'بي بي ال'],
            ['name_en' => 'Braun (company)', 'name_ar' => 'براون'],
            ['name_en' => 'Bravox', 'name_ar' => 'برافوكس'],
            ['name_en' => 'Brother Industries – CM, CP, FAX, MFP, PR, OEE', 'name_ar' => 'بروذر اينديستريس'],
            ['name_en' => 'BT', 'name_ar' => 'بي تي'],
            ['name_en' => 'Buffalo (Melco) – HDD, NW, OEE', 'name_ar' => 'بافالو (ميلكو)'],
            ['name_en' => 'Bush', 'name_ar' => 'بوش'],
            ['name_en' => 'BYD Electronic', 'name_ar' => 'بي واي دي الكترونيك'],
            ['name_en' => 'Canon – CM, DC, DVC, FAX, MFP, PR, OEE', 'name_ar' => 'كانون'],
            ['name_en' => 'Canovate', 'name_ar' => 'كانوفيت'],
            ['name_en' => 'Casio – DC, MP, OEE', 'name_ar' => 'كاسيو'],
            ['name_en' => 'Celkon', 'name_ar' => 'كليكون'],
            ['name_en' => 'Changhong', 'name_ar' => 'تشانغونج'],
            ['name_en' => 'Cisco Systems', 'name_ar' => 'سيسكو سيستمز'],
            ['name_en' => 'Clarion – CA, CN', 'name_ar' => 'كلاريون'],
            ['name_en' => 'Cowon', 'name_ar' => '‏كاون'],
            ['name_en' => 'Daewoo Electronics', 'name_ar' => '‏ دايو اليكترونيك'],
            ['name_en' => 'Dawlance', 'name_ar' => 'داولانس'],
            ['name_en' => 'Dell', 'name_ar' => 'ديل'],
            ['name_en' => 'D-Link', 'name_ar' => '‏ دي لينك'],
            ['name_en' => 'Dyson', 'name_ar' => 'دايسون'],
            ['name_en' => 'ECIL', 'name_ar' => 'اكيل'],
            ['name_en' => 'Eclipse (Fujitsu Ten) ((Fujitsu)) – CA, CN, OEE', 'name_ar' => 'إكلبس'],
            ['name_en' => 'ECS', 'name_ar' => '‏ اي سي اس'],
            ['name_en' => 'Eizo (Eizo Nanao Co.) – DD', 'name_ar' => 'إيزو'],
            ['name_en' => 'Electrolux', 'name_ar' => 'اليكترولكس'],
            ['name_en' => 'Elsa', 'name_ar' => '‏  السا'],
            ['name_en' => 'eMachines', 'name_ar' => 'ايماشينس'],
            ['name_en' => 'Embraer', 'name_ar' => 'إمبراير'],
            ['name_en' => 'Emerson Electric', 'name_ar' => 'ايمرسون الكتريك'],
            ['name_en' => 'Emerson Radio', 'name_ar' => 'ايمرسون راديو'],
            ['name_en' => 'EMI', 'name_ar' => 'ايمي'],
            ['name_en' => 'EPoX', 'name_ar' => '‏ اي بوكس'],
            ['name_en' => 'Epson – CM, FAX, MFP, PR, OEE', 'name_ar' => 'إبسون'],
            ['name_en' => 'Ferranti', 'name_ar' => 'فيرانتي'],
            ['name_en' => 'Foxconn', 'name_ar' => '‏ فوكس كون'],
            ['name_en' => 'Fuji Electric – MN, TES, OEE', 'name_ar' => 'فوجي الكتريك'],
            ['name_en' => 'Fuji Xerox – CM, MFP, OEE', 'name_ar' => 'فوجي زيروكس'],
            ['name_en' => 'Fujifilm – DC', 'name_ar' => 'فوجي فيلم'],
            ['name_en' => 'Fujitsu – CA, CN, CP, MP, NW, PC, SC, OEE', 'name_ar' => 'فوجيتسو'],
            ['name_en' => 'Funai – DVP, DVR, TV, OEE', 'name_ar' => 'فوناي'],
            ['name_en' => 'Gateway', 'name_ar' => 'جيتواي'],
            ['name_en' => 'Geliyoo', 'name_ar' => 'جيليو'],
            ['name_en' => 'Gigabyte', 'name_ar' => '‏ جيجابايت'],
            ['name_en' => 'Gionee', 'name_ar' => 'جيوني'],
            ['name_en' => 'Godrej', 'name_ar' => 'جودريج'],
            ['name_en' => 'Gradiente', 'name_ar' => 'قرادينتي'],
            ['name_en' => 'Grundig', 'name_ar' => 'جروندج'],
            ['name_en' => 'Haier', 'name_ar' => 'هاير'],
            ['name_en' => 'Hansol', 'name_ar' => '‏ هانسل'],
            ['name_en' => 'Hasee', 'name_ar' => 'حسي'],
            ['name_en' => 'Havells', 'name_ar' => 'هافيلس'],
            ['name_en' => 'HCL', 'name_ar' => 'اتش سي ال'],
            ['name_en' => 'Hewlett-Packard', 'name_ar' => 'هوليت باكارد'],
            ['name_en' => 'Hisense', 'name_ar' => 'هايسنس'],
            ['name_en' => 'Hitachi – CP, HDD, SC, TV, TES', 'name_ar' => 'هيتاشي'],
            ['name_en' => 'HTC', 'name_ar' => '‏ اتش تي سي'],
            ['name_en' => 'Huawei', 'name_ar' => 'هواوي'],
            ['name_en' => 'Hungary[edit]', 'name_ar' => 'هانقري'],
            ['name_en' => 'Husqvarna', 'name_ar' => 'هوسكفارنا'],
            ['name_en' => 'iball', 'name_ar' => 'اي بول'],
            ['name_en' => 'IBM', 'name_ar' => 'آي بي إم'],
            ['name_en' => 'Iiyama – DD', 'name_ar' => 'إياما'],
            ['name_en' => 'Intel', 'name_ar' => 'إنتل'],
            ['name_en' => 'Intex', 'name_ar' => 'اينتكس'],
            ['name_en' => 'IO Data – HDD, NW, OEE', 'name_ar' => 'أيو داتا'],
            ['name_en' => 'Iriver', 'name_ar' => '‏ اريفر'],
            ['name_en' => 'Itautec', 'name_ar' => 'إيتوتيك'],
            ['name_en' => 'JBL ', 'name_ar' => 'جي بي ال'],
            ['name_en' => 'JVC (Victor Company of Japan, Ltd) ((JVC Kenwood Holdings)) – AS, CA, CN, DVC, DVP, DVR', 'name_ar' => 'جيه في سي'],
            ['name_en' => 'Karbonn', 'name_ar' => 'كربون'],
            ['name_en' => 'KEF', 'name_ar' => 'كي إي اف'],
            ['name_en' => 'Kenstar', 'name_ar' => 'كينستار'],
            ['name_en' => 'Kenwood ((JVC Kenwood Holdings)) – AS, CA, CN, WD', 'name_ar' => 'كينوود'],
            ['name_en' => 'Khind', 'name_ar' => '‏ كايند'],
            ['name_en' => 'Kingston', 'name_ar' => 'كينغستون'],
            ['name_en' => 'Kongsberg Gruppen', 'name_ar' => 'كونقس بيرق جروبن'],
            ['name_en' => 'Konica Minolta – MFP, OEE', 'name_ar' => 'كونيكا مينولتا'],
            ['name_en' => 'Konka Group', 'name_ar' => 'كونكا قروب'],
            ['name_en' => 'Koss', 'name_ar' => 'كوس'],
            ['name_en' => 'Kyocera – SC, OEE', 'name_ar' => 'كيوسيرا'],
            ['name_en' => 'Kyoto (Kyoto Electronics)', 'name_ar' => 'كيوتو'],
            ['name_en' => 'Lanix', 'name_ar' => 'لانكيس'],
            ['name_en' => 'Lava (also Xolo)', 'name_ar' => 'لافا'],
            ['name_en' => 'Lenovo', 'name_ar' => 'لينوفو'],
            ['name_en' => 'LG', 'name_ar' => '‏ ال جي'],
            ['name_en' => 'Lite-On', 'name_ar' => '‏ لايت اون'],
            ['name_en' => 'lloid', 'name_ar' => 'لويد'],
            ['name_en' => 'Loewe AG', 'name_ar' => 'لويق'],
            ['name_en' => 'Mabe', 'name_ar' => 'مابي'],
            ['name_en' => 'Magnavox', 'name_ar' => 'ماجنافوكس'],
            ['name_en' => 'Marantz ((D&M Holdings)) – AS, WD, OEE', 'name_ar' => 'مارانتز'],
            ['name_en' => 'Marconi', 'name_ar' => 'ماركوني'],
            ['name_en' => 'Mectron', 'name_ar' => 'ميكترون'],
            ['name_en' => 'MediaTek', 'name_ar' => '‏ميديا تيك'],
            ['name_en' => 'Medion', 'name_ar' => 'ميديون'],
            ['name_en' => 'Meebox', 'name_ar' => 'ميبوكس'],
            ['name_en' => 'Meizu', 'name_ar' => 'ميزو'],
            ['name_en' => 'Mentor Graphics', 'name_ar' => 'مينتور جرافيكس'],
            ['name_en' => 'Metz (company)', 'name_ar' => 'ميتز'],
            ['name_en' => 'Micromax', 'name_ar' => 'مايكروماكس'],
            ['name_en' => 'Microsoft', 'name_ar' => 'مايكروسوفت'],
            ['name_en' => 'Miele', 'name_ar' => 'ميلي'],
            ['name_en' => 'Mitron', 'name_ar' => 'ميترون'],
            ['name_en' => 'Mitsubishi (Mitsubishi Electric) ((Mitsubishi Group)) – DD, DVP, DPR, TES, OEE', 'name_ar' => 'ميتسوبيشي'],
            ['name_en' => 'Morphy Richards', 'name_ar' => 'موفي ريتشاردز'],
            ['name_en' => 'Moser Baer', 'name_ar' => 'موسر بير'],
            ['name_en' => 'Motorola', 'name_ar' => 'موتورولا'],
            ['name_en' => 'MSI (Micro-Star International)', 'name_ar' => '‏ام اس اي'],
            ['name_en' => 'Myzornis', 'name_ar' => 'مايزورنيس'],
            ['name_en' => 'NEC – CP, MP, NW, PC, SC', 'name_ar' => 'إن إي سي'],
            ['name_en' => 'Nikon – DC, DVC', 'name_ar' => 'نيكون'],
            ['name_en' => 'Ningbo Bird', 'name_ar' => 'نينغبو بيرد'],
            ['name_en' => 'Nintendo – VG', 'name_ar' => 'نينتندو'],
            ['name_en' => 'Nokia', 'name_ar' => 'نوكيا'],
            ['name_en' => 'Nordic Semiconductor', 'name_ar' => 'نورديسك سيميك اندكتر'],
            ['name_en' => 'Notion Ink', 'name_ar' => 'نوشين ال إن كي'],
            ['name_en' => 'NVIDIA', 'name_ar' => 'إنفيديا'],
            ['name_en' => 'Oki – CP, TES', 'name_ar' => 'أوكي'],
            ['name_en' => 'Olympus – DC, DVC', 'name_ar' => 'أوليمبوس'],
            ['name_en' => 'Onida', 'name_ar' => 'أونيدا'],
            ['name_en' => 'Oppo', 'name_ar' => 'اوبو'],
            ['name_en' => 'Orient Electronics', 'name_ar' => 'اورنت اليكترونكس'],
            ['name_en' => 'Orion (Orion Electric Co.) – DVP, DVR, TV', 'name_ar' => 'أوريون'],
            ['name_en' => 'Orion (Orion Electronics Ltd)', 'name_ar' => 'اوريون'],
            ['name_en' => 'Pace', 'name_ar' => 'بيس'],
            ['name_en' => 'Packard Bell', 'name_ar' => 'باكارد بيل'],
            ['name_en' => 'Pakistan Aeronautical Complex', 'name_ar' => 'باكستان ايروناتيكال كومبلكس'],
            ['name_en' => 'Panasonic – CA, CN, DC, DD, DVC, DVP, DVR, FAX, MP, NW, PC, PMP, SC, TV, WD, OEE', 'name_ar' => 'باناسونيك'],
            ['name_en' => 'Panavox', 'name_ar' => 'بانافوكس'],
            ['name_en' => 'Panda', 'name_ar' => 'بنده'],
            ['name_en' => 'Pantech', 'name_ar' => '‏ بانتيج'],
            ['name_en' => 'Paradox Interactive', 'name_ar' => 'برودقس إنتراكتيف'],
            ['name_en' => 'PEL (Pakistan)', 'name_ar' => 'بي اي ال'],
            ['name_en' => 'Pensonic', 'name_ar' => '‏بينسونيك'],
            ['name_en' => 'Pentax ((Hoya)) – DC', 'name_ar' => 'بينتاكس'],
            ['name_en' => 'Philips', 'name_ar' => 'فيليبس'],
            ['name_en' => 'Pioneer – CA, CN, WD, OEE', 'name_ar' => 'بايونير'],
            ['name_en' => 'Positivo Informatica', 'name_ar' => 'بوزيتيفو إنفورماتيكا'],
            ['name_en' => 'Provision', 'name_ar' => 'بروفيشن'],
            ['name_en' => 'Pure', 'name_ar' => 'بيور'],
            ['name_en' => 'Pye', 'name_ar' => 'باي'],
            ['name_en' => 'QMobile', 'name_ar' => 'كيو موبايل'],
            ['name_en' => 'Qualcomm', 'name_ar' => 'كوالكوم'],
            ['name_en' => 'RCA', 'name_ar' => 'آر سي إيه'],
            ['name_en' => 'Realtek', 'name_ar' => 'ريل تيك'],
            ['name_en' => 'Renesas – SC', 'name_ar' => 'رينيسا'],
            ['name_en' => 'Revox', 'name_ar' => 'ريفوكس'],
            ['name_en' => 'Ricoh – DC, CP, MFP', 'name_ar' => 'ريكوه'],
            ['name_en' => 'Russell Hobbs', 'name_ar' => 'راسل هوبس'],
            ['name_en' => 'Samart', 'name_ar' => '‏ سامارات'],
            ['name_en' => 'Satmex', 'name_ar' => 'ساتميكس'],
            ['name_en' => 'SATUMA', 'name_ar' => 'ساتوما'],
            ['name_en' => 'Seagate', 'name_ar' => 'سيجيت'],
            ['name_en' => 'Sennheiser', 'name_ar' => 'سنهايزر'],
            ['name_en' => 'Severin Elektro', 'name_ar' => 'سيفيرين اليكترو'],
            ['name_en' => 'SGI', 'name_ar' => 'اس جي ال'],
            ['name_en' => 'Sharp – DD, DVC, DVP, DVR, FAX, MP, PC, SC, TV', 'name_ar' => 'شارب'],
            ['name_en' => 'Siemens', 'name_ar' => 'سيمنز'],
            ['name_en' => 'Siemens Pakistan', 'name_ar' => 'سيمينس باكستان'],
            ['name_en' => 'SII (Seiko Instruments Inc.) – OEE', 'name_ar' => 'سي'],
            ['name_en' => 'Silicon Power', 'name_ar' => 'سيليكون باور'],
            ['name_en' => 'Simmtronics', 'name_ar' => 'سيمترونيكس'],
            ['name_en' => 'Sinclair Research', 'name_ar' => 'سينكلير ريتش'],
            ['name_en' => 'Singer', 'name_ar' => '‏ سينقر'],
            ['name_en' => 'Skyworth', 'name_ar' => 'سكاي وورث'],
            ['name_en' => 'Sony – CA, CN, DC, DD, DVC, DVP, DVR, GPS, PC, PMP, SC, TV, VG, WD, OED', 'name_ar' => 'سوني'],
            ['name_en' => 'Soyo', 'name_ar' => 'سويو'],
            ['name_en' => 'Sterlite Technologies', 'name_ar' => 'ستيرلايت تكلونوجي'],
            ['name_en' => 'Sun Microsystems', 'name_ar' => 'صن ميكروسيستيمز'],
            ['name_en' => 'Super Asia (Pakistan)', 'name_ar' => '‏سوبر اسيا'],
            ['name_en' => 'TCL', 'name_ar' => 'تي سي ال'],
            ['name_en' => 'TDK – SC, OEE', 'name_ar' => 'تي دي كي'],
            ['name_en' => 'TechniSat', 'name_ar' => 'تكنيسات'],
            ['name_en' => 'Texas Instruments', 'name_ar' => 'تكساس إنسترومنتس'],
            ['name_en' => 'Texet', 'name_ar' => 'تيكست'],
            ['name_en' => 'Thorn', 'name_ar' => 'ثورن'],
            ['name_en' => 'Toshiba – CP, DD, DVC, DVP, DVR, PC, SC, TES, TV, OED', 'name_ar' => 'توشيبا'],
            ['name_en' => 'TP-Linkintex', 'name_ar' => 'تي بي لينكنتس'],
            ['name_en' => 'Trust', 'name_ar' => 'ترست'],
            ['name_en' => 'Undefined/NA', 'name_ar' => 'اينديفيدن'],
            ['name_en' => 'Uniross', 'name_ar' => 'يونيروس'],
            ['name_en' => 'Unisonic Products Corporation', 'name_ar' => 'شركة منتجات يونيسنيك'],
            ['name_en' => 'Unisys', 'name_ar' => 'يونيسيس'],
            ['name_en' => 'United Mobile', 'name_ar' => 'يونايتد موبايل'],
            ['name_en' => 'Vax', 'name_ar' => 'فاكس'],
            ['name_en' => 'Vertex Standard – GPS, WD', 'name_ar' => 'فيترتكس ستاندارت'],
            ['name_en' => 'Vestel', 'name_ar' => 'فستيل'],
            ['name_en' => 'Victor (Victor Company of Japan, Ltd) ((JVC Kenwood Holdings)) – Same as JVC', 'name_ar' => 'فيكتور'],
            ['name_en' => 'Videocon', 'name_ar' => 'فيديوكون'],
            ['name_en' => 'Videotex', 'name_ar' => 'فيديوتكس'],
            ['name_en' => 'Videoton', 'name_ar' => 'فيديوتون'],
            ['name_en' => 'Viewsonic', 'name_ar' => 'فيوسونيك'],
            ['name_en' => 'Viper Technology', 'name_ar' => 'ڤايبر تيكنولوجي'],
            ['name_en' => 'Vivo Electronics', 'name_ar' => 'فيفو اليكترونيكس'],
            ['name_en' => 'Vizio', 'name_ar' => 'فيزيو'],
            ['name_en' => 'Voice Mobile', 'name_ar' => 'فويس موبايل'],
            ['name_en' => 'Voltas', 'name_ar' => 'فولتاس'],
            ['name_en' => 'WEG Industries', 'name_ar' => 'ويج ايندرستينس'],
            ['name_en' => 'Western Digital', 'name_ar' => 'ويسترن ديجيتال'],
            ['name_en' => 'Wilfa', 'name_ar' => 'ويلفا'],
            ['name_en' => 'Wipro', 'name_ar' => 'ويبرو'],
            ['name_en' => 'Wortmann', 'name_ar' => 'وورتمان'],
            ['name_en' => 'Xerox', 'name_ar' => 'زيروكس'],
            ['name_en' => 'Xiaomi', 'name_ar' => 'شاومي'],
            ['name_en' => 'Yaesu (Vertex Standard) – same as Vertex Standard', 'name_ar' => 'ياسو'],
            ['name_en' => 'zebronics', 'name_ar' => 'زيبرونكس'],
            ['name_en' => 'Zenith', 'name_ar' => 'زينيث'],
            ['name_en' => 'Zonda (Zonda Telecom)', 'name_ar' => 'زوندا'],
            ['name_en' => 'Zopo Mobile', 'name_ar' => 'زوبو موبايل'],
            ['name_en' => 'ZTE', 'name_ar' => 'زد تي إي'],
            ['name_en' => 'TRUE', 'name_ar' => 'ترو'],
        ];
        $category = Category::find(1);
        foreach ($data as $item){
            $brand = Brand::create($item);

            foreach ($category->subcategories as $subcategory){
                $subcategory->brands()->attach($brand);
            }
        }



        $this->info('|----------------------------------|');
        $this->info('| Seeding Electronics Done Successfully |');
        $this->info('|----------------------------------|');
    }
}
