<?php

namespace App\Console\Commands;

use App\Category;
use App\SubCategory;
use Illuminate\Console\Command;

class FillBrands extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'fill:brands';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $data = array(
            array('name_en' => '3M', 'name_ar' => 'ثري ام'),
            array('name_en' => 'Acer', 'name_ar' => '‏  اسير'),
            array('name_en' => 'Aigo ', 'name_ar' => 'ايجو'),
            array('name_en' => 'Alba', 'name_ar' => 'البا'),
            array('name_en' => 'Alfa', 'name_ar' => 'الفا'),
            array('name_en' => 'Allied Telesis – NW, OEE', 'name_ar' => 'آليد تليسيس'),
            array('name_en' => 'Alpine – CA, CN', 'name_ar' => 'البين'),
            array('name_en' => 'Amazon', 'name_ar' => 'امازون'),
            array('name_en' => 'AMD', 'name_ar' => 'اي ام دي'),
            array('name_en' => 'Amkette', 'name_ar' => 'أمكيت'),
            array('name_en' => 'Amoi', 'name_ar' => 'اومي'),
            array('name_en' => 'Amstrad', 'name_ar' => 'امستراد'),
            array('name_en' => 'Analog Devices', 'name_ar' => 'انالوق ديفيفس'),
            array('name_en' => 'AOC (AOC International) ((TPV Technology Limited))', 'name_ar' => 'اوسي'),
            array('name_en' => 'Aopen', 'name_ar' => '‏  اوبن'),
            array('name_en' => 'Apple', 'name_ar' => 'ابل'),
            array('name_en' => 'Arçelik', 'name_ar' => 'أرتشيليك'),
            array('name_en' => 'Aselsan', 'name_ar' => 'اسيلسان'),
            array('name_en' => 'Asus', 'name_ar' => 'اسوس'),
            array('name_en' => 'Audiovox', 'name_ar' => 'أوديوفوكس'),
            array('name_en' => 'Avaya', 'name_ar' => 'افايا'),
            array('name_en' => 'Averatec', 'name_ar' => 'افراتيك'),
            array('name_en' => 'Avibras', 'name_ar' => 'أفبراس'),
            array('name_en' => 'BAE Systems', 'name_ar' => 'بي أيه أي سيستمز'),
            array('name_en' => 'Beetel', 'name_ar' => 'بيتل'),
            array('name_en' => 'Beko', 'name_ar' => 'بيكو'),
            array('name_en' => 'BenQ', 'name_ar' => '‏  بين كيو'),
            array('name_en' => 'Bharat Electronics', 'name_ar' => 'بارات اليكترونيكس'),
            array('name_en' => 'Binatone', 'name_ar' => 'بيناتون'),
            array('name_en' => 'BlackBerry Limited (as BlackBerry)', 'name_ar' => 'بلاك بيري لمتد'),
            array('name_en' => 'Blaupunkt', 'name_ar' => 'بلوبونكت'),
            array('name_en' => 'Bosch', 'name_ar' => 'بوش'),
            array('name_en' => 'Bose', 'name_ar' => 'بوز'),
            array('name_en' => 'Bose', 'name_ar' => 'بوز'),
            array('name_en' => 'BPL', 'name_ar' => 'بي بي ال'),
            array('name_en' => 'Braun (company)', 'name_ar' => 'براون'),
            array('name_en' => 'Bravox', 'name_ar' => 'برافوكس'),
            array('name_en' => 'Brother Industries – CM, CP, FAX, MFP, PR, OEE', 'name_ar' => 'بروذر اينديستريس'),
            array('name_en' => 'BT', 'name_ar' => 'بي تي'),
            array('name_en' => 'Buffalo (Melco) – HDD, NW, OEE', 'name_ar' => 'بافالو (ميلكو)'),
            array('name_en' => 'Bush', 'name_ar' => 'بوش'),
            array('name_en' => 'BYD Electronic', 'name_ar' => 'بي واي دي الكترونيك'),
            array('name_en' => 'Canon – CM, DC, DVC, FAX, MFP, PR, OEE', 'name_ar' => 'كانون'),
            array('name_en' => 'Canovate', 'name_ar' => 'كانوفيت'),
            array('name_en' => 'Casio – DC, MP, OEE', 'name_ar' => 'كاسيو'),
            array('name_en' => 'Celkon', 'name_ar' => 'كليكون'),
            array('name_en' => 'Changhong', 'name_ar' => 'تشانغونج'),
            array('name_en' => 'Cisco Systems', 'name_ar' => 'سيسكو سيستمز'),
            array('name_en' => 'Clarion – CA, CN', 'name_ar' => 'كلاريون'),
            array('name_en' => 'Cowon', 'name_ar' => '‏كاون'),
            array('name_en' => 'Daewoo Electronics', 'name_ar' => '‏ دايو اليكترونيك'),
            array('name_en' => 'Dawlance', 'name_ar' => 'داولانس'),
            array('name_en' => 'Dell', 'name_ar' => 'ديل'),
            array('name_en' => 'D-Link', 'name_ar' => '‏ دي لينك'),
            array('name_en' => 'Dyson', 'name_ar' => 'دايسون'),
            array('name_en' => 'ECIL', 'name_ar' => 'اكيل'),
            array('name_en' => 'Eclipse (Fujitsu Ten) ((Fujitsu)) – CA, CN, OEE', 'name_ar' => 'إكلبس'),
            array('name_en' => 'ECS', 'name_ar' => '‏ اي سي اس'),
            array('name_en' => 'Eizo (Eizo Nanao Co.) – DD', 'name_ar' => 'إيزو'),
            array('name_en' => 'Electrolux', 'name_ar' => 'اليكترولكس'),
            array('name_en' => 'Elsa', 'name_ar' => '‏  السا'),
            array('name_en' => 'eMachines', 'name_ar' => 'ايماشينس'),
            array('name_en' => 'Embraer', 'name_ar' => 'إمبراير'),
            array('name_en' => 'Emerson Electric', 'name_ar' => 'ايمرسون الكتريك'),
            array('name_en' => 'Emerson Radio', 'name_ar' => 'ايمرسون راديو'),
            array('name_en' => 'EMI', 'name_ar' => 'ايمي'),
            array('name_en' => 'EPoX', 'name_ar' => '‏ اي بوكس'),
            array('name_en' => 'Epson – CM, FAX, MFP, PR, OEE', 'name_ar' => 'إبسون'),
            array('name_en' => 'Ferranti', 'name_ar' => 'فيرانتي'),
            array('name_en' => 'Foxconn', 'name_ar' => '‏ فوكس كون'),
            array('name_en' => 'Fuji Electric – MN, TES, OEE', 'name_ar' => 'فوجي الكتريك'),
            array('name_en' => 'Fuji Xerox – CM, MFP, OEE', 'name_ar' => 'فوجي زيروكس'),
            array('name_en' => 'Fujifilm – DC', 'name_ar' => 'فوجي فيلم'),
            array('name_en' => 'Fujitsu – CA, CN, CP, MP, NW, PC, SC, OEE', 'name_ar' => 'فوجيتسو'),
            array('name_en' => 'Funai – DVP, DVR, TV, OEE', 'name_ar' => 'فوناي'),
            array('name_en' => 'Gateway', 'name_ar' => 'جيتواي'),
            array('name_en' => 'Geliyoo', 'name_ar' => 'جيليو'),
            array('name_en' => 'Gigabyte', 'name_ar' => '‏ جيجابايت'),
            array('name_en' => 'Gionee', 'name_ar' => 'جيوني'),
            array('name_en' => 'Godrej', 'name_ar' => 'جودريج'),
            array('name_en' => 'Gradiente', 'name_ar' => 'قرادينتي'),
            array('name_en' => 'Grundig', 'name_ar' => 'جروندج'),
            array('name_en' => 'Haier', 'name_ar' => 'هاير'),
            array('name_en' => 'Hansol', 'name_ar' => '‏ هانسل'),
            array('name_en' => 'Hasee', 'name_ar' => 'حسي'),
            array('name_en' => 'Havells', 'name_ar' => 'هافيلس'),
            array('name_en' => 'HCL', 'name_ar' => 'اتش سي ال'),
            array('name_en' => 'Hewlett-Packard', 'name_ar' => 'هوليت باكارد'),
            array('name_en' => 'Hisense', 'name_ar' => 'هايسنس'),
            array('name_en' => 'Hitachi – CP, HDD, SC, TV, TES', 'name_ar' => 'هيتاشي'),
            array('name_en' => 'HTC', 'name_ar' => '‏ اتش تي سي'),
            array('name_en' => 'Huawei', 'name_ar' => 'هواوي'),
            array('name_en' => 'Hungary[edit]', 'name_ar' => 'هانقري'),
            array('name_en' => 'Husqvarna', 'name_ar' => 'هوسكفارنا'),
            array('name_en' => 'iball', 'name_ar' => 'اي بول'),
            array('name_en' => 'IBM', 'name_ar' => 'آي بي إم'),
            array('name_en' => 'Iiyama – DD', 'name_ar' => 'إياما'),
            array('name_en' => 'Intel', 'name_ar' => 'إنتل'),
            array('name_en' => 'Intex', 'name_ar' => 'اينتكس'),
            array('name_en' => 'IO Data – HDD, NW, OEE', 'name_ar' => 'أيو داتا'),
            array('name_en' => 'Iriver', 'name_ar' => '‏ اريفر'),
            array('name_en' => 'Itautec', 'name_ar' => 'إيتوتيك'),
            array('name_en' => 'JBL ', 'name_ar' => 'جي بي ال'),
            array('name_en' => 'JVC (Victor Company of Japan, Ltd) ((JVC Kenwood Holdings)) – AS, CA, CN, DVC, DVP, DVR', 'name_ar' => 'جيه في سي'),
            array('name_en' => 'Karbonn', 'name_ar' => 'كربون'),
            array('name_en' => 'KEF', 'name_ar' => 'كي إي اف'),
            array('name_en' => 'Kenstar', 'name_ar' => 'كينستار'),
            array('name_en' => 'Kenwood ((JVC Kenwood Holdings)) – AS, CA, CN, WD', 'name_ar' => 'كينوود'),
            array('name_en' => 'Khind', 'name_ar' => '‏ كايند'),
            array('name_en' => 'Kingston', 'name_ar' => 'كينغستون'),
            array('name_en' => 'Kongsberg Gruppen', 'name_ar' => 'كونقس بيرق جروبن'),
            array('name_en' => 'Konica Minolta – MFP, OEE', 'name_ar' => 'كونيكا مينولتا'),
            array('name_en' => 'Konka Group', 'name_ar' => 'كونكا قروب'),
            array('name_en' => 'Koss', 'name_ar' => 'كوس'),
            array('name_en' => 'Kyocera – SC, OEE', 'name_ar' => 'كيوسيرا'),
            array('name_en' => 'Kyoto (Kyoto Electronics)', 'name_ar' => 'كيوتو'),
            array('name_en' => 'Lanix', 'name_ar' => 'لانكيس'),
            array('name_en' => 'Lava (also Xolo)', 'name_ar' => 'لافا'),
            array('name_en' => 'Lenovo', 'name_ar' => 'لينوفو'),
            array('name_en' => 'LG', 'name_ar' => '‏ ال جي'),
            array('name_en' => 'Lite-On', 'name_ar' => '‏ لايت اون'),
            array('name_en' => 'lloid', 'name_ar' => 'لويد'),
            array('name_en' => 'Loewe AG', 'name_ar' => 'لويق'),
            array('name_en' => 'Mabe', 'name_ar' => 'مابي'),
            array('name_en' => 'Magnavox', 'name_ar' => 'ماجنافوكس'),
            array('name_en' => 'Marantz ((D&M Holdings)) – AS, WD, OEE', 'name_ar' => 'مارانتز'),
            array('name_en' => 'Marconi', 'name_ar' => 'ماركوني'),
            array('name_en' => 'Mectron', 'name_ar' => 'ميكترون'),
            array('name_en' => 'MediaTek', 'name_ar' => '‏ميديا تيك'),
            array('name_en' => 'Medion', 'name_ar' => 'ميديون'),
            array('name_en' => 'Meebox', 'name_ar' => 'ميبوكس'),
            array('name_en' => 'Meizu', 'name_ar' => 'ميزو'),
            array('name_en' => 'Mentor Graphics', 'name_ar' => 'مينتور جرافيكس'),
            array('name_en' => 'Metz (company)', 'name_ar' => 'ميتز'),
            array('name_en' => 'Micromax', 'name_ar' => 'مايكروماكس'),
            array('name_en' => 'Microsoft', 'name_ar' => 'مايكروسوفت'),
            array('name_en' => 'Miele', 'name_ar' => 'ميلي'),
            array('name_en' => 'Mitron', 'name_ar' => 'ميترون'),
            array('name_en' => 'Mitsubishi (Mitsubishi Electric) ((Mitsubishi Group)) – DD, DVP, DPR, TES, OEE', 'name_ar' => 'ميتسوبيشي'),
            array('name_en' => 'Morphy Richards', 'name_ar' => 'موفي ريتشاردز'),
            array('name_en' => 'Moser Baer', 'name_ar' => 'موسر بير'),
            array('name_en' => 'Motorola', 'name_ar' => 'موتورولا'),
            array('name_en' => 'MSI (Micro-Star International)', 'name_ar' => '‏ام اس اي'),
            array('name_en' => 'Myzornis', 'name_ar' => 'مايزورنيس'),
            array('name_en' => 'NEC – CP, MP, NW, PC, SC', 'name_ar' => 'إن إي سي'),
            array('name_en' => 'Nikon – DC, DVC', 'name_ar' => 'نيكون'),
            array('name_en' => 'Ningbo Bird', 'name_ar' => 'نينغبو بيرد'),
            array('name_en' => 'Nintendo – VG', 'name_ar' => 'نينتندو'),
            array('name_en' => 'Nokia', 'name_ar' => 'نوكيا'),
            array('name_en' => 'Nordic Semiconductor', 'name_ar' => 'نورديسك سيميك اندكتر'),
            array('name_en' => 'Notion Ink', 'name_ar' => 'نوشين ال إن كي'),
            array('name_en' => 'NVIDIA', 'name_ar' => 'إنفيديا'),
            array('name_en' => 'Oki – CP, TES', 'name_ar' => 'أوكي'),
            array('name_en' => 'Olympus – DC, DVC', 'name_ar' => 'أوليمبوس'),
            array('name_en' => 'Onida', 'name_ar' => 'أونيدا'),
            array('name_en' => 'Oppo', 'name_ar' => 'اوبو'),
            array('name_en' => 'Orient Electronics', 'name_ar' => 'اورنت اليكترونكس'),
            array('name_en' => 'Orion (Orion Electric Co.) – DVP, DVR, TV', 'name_ar' => 'أوريون'),
            array('name_en' => 'Orion (Orion Electronics Ltd)', 'name_ar' => 'اوريون'),
            array('name_en' => 'Pace', 'name_ar' => 'بيس'),
            array('name_en' => 'Packard Bell', 'name_ar' => 'باكارد بيل'),
            array('name_en' => 'Pakistan Aeronautical Complex', 'name_ar' => 'باكستان ايروناتيكال كومبلكس'),
            array('name_en' => 'Panasonic – CA, CN, DC, DD, DVC, DVP, DVR, FAX, MP, NW, PC, PMP, SC, TV, WD, OEE', 'name_ar' => 'باناسونيك'),
            array('name_en' => 'Panavox', 'name_ar' => 'بانافوكس'),
            array('name_en' => 'Panda', 'name_ar' => 'بنده'),
            array('name_en' => 'Pantech', 'name_ar' => '‏ بانتيج'),
            array('name_en' => 'Paradox Interactive', 'name_ar' => 'برودقس إنتراكتيف'),
            array('name_en' => 'PEL (Pakistan)', 'name_ar' => 'بي اي ال'),
            array('name_en' => 'Pensonic', 'name_ar' => '‏بينسونيك'),
            array('name_en' => 'Pentax ((Hoya)) – DC', 'name_ar' => 'بينتاكس'),
            array('name_en' => 'Philips', 'name_ar' => 'فيليبس'),
            array('name_en' => 'Pioneer – CA, CN, WD, OEE', 'name_ar' => 'بايونير'),
            array('name_en' => 'Positivo Informatica', 'name_ar' => 'بوزيتيفو إنفورماتيكا'),
            array('name_en' => 'Provision', 'name_ar' => 'بروفيشن'),
            array('name_en' => 'Pure', 'name_ar' => 'بيور'),
            array('name_en' => 'Pye', 'name_ar' => 'باي'),
            array('name_en' => 'QMobile', 'name_ar' => 'كيو موبايل'),
            array('name_en' => 'Qualcomm', 'name_ar' => 'كوالكوم'),
            array('name_en' => 'RCA', 'name_ar' => 'آر سي إيه'),
            array('name_en' => 'Realtek', 'name_ar' => 'ريل تيك'),
            array('name_en' => 'Renesas – SC', 'name_ar' => 'رينيسا'),
            array('name_en' => 'Revox', 'name_ar' => 'ريفوكس'),
            array('name_en' => 'Ricoh – DC, CP, MFP', 'name_ar' => 'ريكوه'),
            array('name_en' => 'Russell Hobbs', 'name_ar' => 'راسل هوبس'),
            array('name_en' => 'Samart', 'name_ar' => '‏ سامارات'),
            array('name_en' => 'Satmex', 'name_ar' => 'ساتميكس'),
            array('name_en' => 'SATUMA', 'name_ar' => 'ساتوما'),
            array('name_en' => 'Seagate', 'name_ar' => 'سيجيت'),
            array('name_en' => 'Sennheiser', 'name_ar' => 'سنهايزر'),
            array('name_en' => 'Severin Elektro', 'name_ar' => 'سيفيرين اليكترو'),
            array('name_en' => 'SGI', 'name_ar' => 'اس جي ال'),
            array('name_en' => 'Sharp – DD, DVC, DVP, DVR, FAX, MP, PC, SC, TV', 'name_ar' => 'شارب'),
            array('name_en' => 'Siemens', 'name_ar' => 'سيمنز'),
            array('name_en' => 'Siemens Pakistan', 'name_ar' => 'سيمينس باكستان'),
            array('name_en' => 'SII (Seiko Instruments Inc.) – OEE', 'name_ar' => 'سي'),
            array('name_en' => 'Silicon Power', 'name_ar' => 'سيليكون باور'),
            array('name_en' => 'Simmtronics', 'name_ar' => 'سيمترونيكس'),
            array('name_en' => 'Sinclair Research', 'name_ar' => 'سينكلير ريتش'),
            array('name_en' => 'Singer', 'name_ar' => '‏ سينقر'),
            array('name_en' => 'Skyworth', 'name_ar' => 'سكاي وورث'),
            array('name_en' => 'Sony – CA, CN, DC, DD, DVC, DVP, DVR, GPS, PC, PMP, SC, TV, VG, WD, OED', 'name_ar' => 'سوني'),
            array('name_en' => 'Soyo', 'name_ar' => 'سويو'),
            array('name_en' => 'Sterlite Technologies', 'name_ar' => 'ستيرلايت تكلونوجي'),
            array('name_en' => 'Sun Microsystems', 'name_ar' => 'صن ميكروسيستيمز'),
            array('name_en' => 'Super Asia (Pakistan)', 'name_ar' => '‏سوبر اسيا'),
            array('name_en' => 'TCL', 'name_ar' => 'تي سي ال'),
            array('name_en' => 'TDK – SC, OEE', 'name_ar' => 'تي دي كي'),
            array('name_en' => 'TechniSat', 'name_ar' => 'تكنيسات'),
            array('name_en' => 'Texas Instruments', 'name_ar' => 'تكساس إنسترومنتس'),
            array('name_en' => 'Texet', 'name_ar' => 'تيكست'),
            array('name_en' => 'Thorn', 'name_ar' => 'ثورن'),
            array('name_en' => 'Toshiba – CP, DD, DVC, DVP, DVR, PC, SC, TES, TV, OED', 'name_ar' => 'توشيبا'),
            array('name_en' => 'TP-Linkintex', 'name_ar' => 'تي بي لينكنتس'),
            array('name_en' => 'Trust', 'name_ar' => 'ترست'),
            array('name_en' => 'Undefined/NA', 'name_ar' => 'اينديفيدن'),
            array('name_en' => 'Uniross', 'name_ar' => 'يونيروس'),
            array('name_en' => 'Unisonic Products Corporation', 'name_ar' => 'شركة منتجات يونيسنيك'),
            array('name_en' => 'Unisys', 'name_ar' => 'يونيسيس'),
            array('name_en' => 'United Mobile', 'name_ar' => 'يونايتد موبايل'),
            array('name_en' => 'Vax', 'name_ar' => 'فاكس'),
            array('name_en' => 'Vertex Standard – GPS, WD', 'name_ar' => 'فيترتكس ستاندارت'),
            array('name_en' => 'Vestel', 'name_ar' => 'فستيل'),
            array('name_en' => 'Victor (Victor Company of Japan, Ltd) ((JVC Kenwood Holdings)) – Same as JVC', 'name_ar' => 'فيكتور'),
            array('name_en' => 'Videocon', 'name_ar' => 'فيديوكون'),
            array('name_en' => 'Videotex', 'name_ar' => 'فيديوتكس'),
            array('name_en' => 'Videoton', 'name_ar' => 'فيديوتون'),
            array('name_en' => 'Viewsonic', 'name_ar' => 'فيوسونيك'),
            array('name_en' => 'Viper Technology', 'name_ar' => 'ڤايبر تيكنولوجي'),
            array('name_en' => 'Vivo Electronics', 'name_ar' => 'فيفو اليكترونيكس'),
            array('name_en' => 'Vizio', 'name_ar' => 'فيزيو'),
            array('name_en' => 'Voice Mobile', 'name_ar' => 'فويس موبايل'),
            array('name_en' => 'Voltas', 'name_ar' => 'فولتاس'),
            array('name_en' => 'WEG Industries', 'name_ar' => 'ويج ايندرستينس'),
            array('name_en' => 'Western Digital', 'name_ar' => 'ويسترن ديجيتال'),
            array('name_en' => 'Wilfa', 'name_ar' => 'ويلفا'),
            array('name_en' => 'Wipro', 'name_ar' => 'ويبرو'),
            array('name_en' => 'Wortmann', 'name_ar' => 'وورتمان'),
            array('name_en' => 'Xerox', 'name_ar' => 'زيروكس'),
            array('name_en' => 'Xiaomi', 'name_ar' => 'شاومي'),
            array('name_en' => 'Yaesu (Vertex Standard) – same as Vertex Standard', 'name_ar' => 'ياسو'),
            array('name_en' => 'zebronics', 'name_ar' => 'زيبرونكس'),
            array('name_en' => 'Zenith', 'name_ar' => 'زينيث'),
            array('name_en' => 'Zonda (Zonda Telecom)', 'name_ar' => 'زوندا'),
            array('name_en' => 'Zopo Mobile', 'name_ar' => 'زوبو موبايل'),
            array('name_en' => 'ZTE', 'name_ar' => 'زد تي إي'),
            array('name_en' => '1', 'name_ar' => 'ترو'),
        );
        $category = Category::find(1);
        foreach ($category->subcategories() as $subcategory){
            $subcategory->brands()->createMany($data);
        }



        $this->info('|----------------------------------|');
        $this->info('| Seeding Electronics Done Successfully |');
        $this->info('|----------------------------------|');
    }
}
